// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.SAPCENTERDBModelsEF;

public partial class Agentssap
{
    public int Matricule { get; set; }

    public string NomEtPrenoms { get; set; }

    public string Codefille { get; set; }

    public string Siglefille { get; set; }

    public string Libfille { get; set; }

    public string Codeposte { get; set; }

    public string Poste { get; set; }

    public string Fonction { get; set; }

    public string Persg { get; set; }

    public string Codeparent { get; set; }

    public string Sigleparent { get; set; }

    public string Libelleparent { get; set; }

    public int Centrecout { get; set; }

    public string Mail { get; set; }

    public string Categorie { get; set; }

    public long? Datedebut { get; set; }

    public long? Datefin { get; set; }

    public string Sigledivision { get; set; }

    public string Sigledirection { get; set; }

    public string Codetype { get; set; }

    public string Centre { get; set; }
}