// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Gestions_des_Titres_de_Transport.SAPCENTERDBModelsEF;

public partial class SAPCENTERDBContext : DbContext
{
    public SAPCENTERDBContext(DbContextOptions<SAPCENTERDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Agentssap> Agentssap { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Agentssap>(entity =>
        {
            entity
                .HasNoKey()
                .ToView("AGENTSSAP", "dbo");

            entity.Property(e => e.Categorie)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.Centre)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("CENTRE");
            entity.Property(e => e.Centrecout).HasColumnName("CENTRECOUT");
            entity.Property(e => e.Codefille)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("CODEFILLE");
            entity.Property(e => e.Codeparent)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("CODEPARENT");
            entity.Property(e => e.Codeposte)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("CODEPOSTE");
            entity.Property(e => e.Codetype)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("CODETYPE");
            entity.Property(e => e.Datedebut).HasColumnName("DATEDEBUT");
            entity.Property(e => e.Datefin).HasColumnName("DATEFIN");
            entity.Property(e => e.Fonction)
                .HasMaxLength(500)
                .HasColumnName("FONCTION");
            entity.Property(e => e.Libelleparent)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("LIBELLEPARENT");
            entity.Property(e => e.Libfille)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("LIBFILLE");
            entity.Property(e => e.Mail)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("MAIL");
            entity.Property(e => e.Matricule).HasColumnName("MATRICULE");
            entity.Property(e => e.NomEtPrenoms)
                .HasMaxLength(80)
                .HasColumnName("Nom et Prénoms");
            entity.Property(e => e.Persg)
                .HasMaxLength(10)
                .IsUnicode(false)
                .HasColumnName("PERSG");
            entity.Property(e => e.Poste)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("POSTE");
            entity.Property(e => e.Sigledirection)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("SIGLEDIRECTION");
            entity.Property(e => e.Sigledivision)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("SIGLEDIVISION");
            entity.Property(e => e.Siglefille)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("SIGLEFILLE");
            entity.Property(e => e.Sigleparent)
                .HasMaxLength(20)
                .IsUnicode(false)
                .HasColumnName("SIGLEPARENT");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}