// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.TitreDeTransportModelsEF;

public partial class Agencevoyage
{
    public int Idagencevoyage { get; set; }

    public string Libelleagencevoyage { get; set; }

    public int Matagentenragencevoyage { get; set; }

    public DateTime Dateagentenragencevoyage { get; set; }

    public virtual ICollection<Titredetransport> Titredetransport { get; set; } = new List<Titredetransport>();
}