// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.TitreDeTransportModelsEF;

public partial class Autorisationrole
{
    public int Idroleauto { get; set; }

    public int Idroleutilisateur { get; set; }

    public int Matagentroleauto { get; set; }

    public DateTime Dateexpirationroleauto { get; set; }

    public DateTime Dateattributionroleauto { get; set; }

    public virtual Roleutilisateur IdroleutilisateurNavigation { get; set; }
}