// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.TitreDeTransportModelsEF;

public partial class Autorisationetape
{
    public int Idautoetape { get; set; }

    public int Idetape { get; set; }

    public bool? Simodification { get; set; }

    public bool? Siconsul { get; set; }

    public bool? Sisuppression { get; set; }

    public int Matagentautoetape { get; set; }

    public DateTime Dateexpirationautoetape { get; set; }

    public DateTime Dateattributionautoetape { get; set; }

    public virtual Etape IdetapeNavigation { get; set; }
}