// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.TitreDeTransportModelsEF;

public partial class Avoir
{
    public int Idavoir { get; set; }

    public int? Idbeavoir { get; set; }

    public string Numeroagenceavoir { get; set; }

    public DateTime? Daterecavoir { get; set; }

    public DateTime? Dateagenceemissionavoir { get; set; }

    public decimal? Montanttotalsuravoir { get; set; }

    public string Obseravoir { get; set; }

    public DateTime Datesaisiavoir { get; set; }

    public DateTime? Datevalavoir { get; set; }

    public int Matagentsaiavoir { get; set; }

    public int? Matagentvalavoir { get; set; }

    public int Idetapeavoir { get; set; }

    public int Idagencedevoyageavoir { get; set; }

    public int? Idrenvoiavoir { get; set; }

    public virtual Beavoir IdbeavoirNavigation { get; set; }

    public virtual ICollection<Remboursement> Remboursement { get; set; } = new List<Remboursement>();
}