// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.TitreDeTransportModelsEF;

public partial class Bereglement
{
    public int Idbereglem { get; set; }

    public DateTime? Datevalber { get; set; }

    public DateTime Datesaiber { get; set; }

    public string Obserber { get; set; }

    public int Matagentsaiber { get; set; }

    public int? Matagentvalber { get; set; }

    public int Idetapeber { get; set; }

    public int? Idrenvoiber { get; set; }

    public int Idagencevoyageber { get; set; }

    public virtual ICollection<Facture> Facture { get; set; } = new List<Facture>();
}