// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.TitreDeTransportModelsEF;

public partial class Bondepassage
{
    public int Idbonp { get; set; }

    public DateTime? Datevalbonp { get; set; }

    public DateTime Datesaibonp { get; set; }

    public int Matagentsaibonp { get; set; }

    public int? Matagentvalbonp { get; set; }

    public string Obserbonp { get; set; }

    public int Idetapebonp { get; set; }

    public int? Idrenvoibonp { get; set; }

    public int Idagencevoyagebonp { get; set; }

    public virtual ICollection<Titredetransport> Titredetransport { get; set; } = new List<Titredetransport>();
}