// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.TitreDeTransportModelsEF;

public partial class Classevoyage
{
    public int Idclasse { get; set; }

    public string Libelleclasse { get; set; }

    public int Matagentenrclasse { get; set; }

    public DateTime Dateagentenrclasse { get; set; }

    public virtual ICollection<Titredetransport> Titredetransport { get; set; } = new List<Titredetransport>();
}