// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.TitreDeTransportModelsEF;

public partial class Compagnie
{
    public int Idcompagnie { get; set; }

    public string Libellecompagnie { get; set; }

    public int Matagentenrcomapgnie { get; set; }

    public DateTime Dateagentenrcompagnie { get; set; }

    public virtual ICollection<Titredetransport> Titredetransport { get; set; } = new List<Titredetransport>();
}