// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.TitreDeTransportModelsEF;

public partial class Piecejointe
{
    public int Idpiecej { get; set; }

    public string Nompiecej { get; set; }

    public int Idetapepiecej { get; set; }

    public int? Idtitrepiecej { get; set; }

    public int? Idavoirpiecej { get; set; }

    public int? Idfacturepiecej { get; set; }

    public int Matagentenrpiecej { get; set; }

    public DateTime Dateenrpiecej { get; set; }
}