// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.TitreDeTransportModelsEF;

public partial class Remboursement
{
    public int Idremb { get; set; }

    public int? Idavoir { get; set; }

    public decimal? Montantremb { get; set; }

    public decimal? Montantgapremb { get; set; }

    public bool? Siremboursable { get; set; }

    public bool? Sirembourse { get; set; }

    public string Motifsinonremb { get; set; }

    public string Routingnonutiliser { get; set; }

    public int Matagentsairemb { get; set; }

    public int? Matagentvalremb { get; set; }

    public DateTime Datesairemb { get; set; }

    public DateTime? Datevalremb { get; set; }

    public int Idetaperemb { get; set; }

    public int? Idrenvoiremb { get; set; }

    public string Observationremb { get; set; }

    public virtual Avoir IdavoirNavigation { get; set; }

    public virtual ICollection<Titredetransport> Titredetransport { get; set; } = new List<Titredetransport>();
}