// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.TitreDeTransportModelsEF;

public partial class Renvoi
{
    public int Idrenvoi { get; set; }

    public string Motifrenvoi { get; set; }

    public DateTime Daterenvoi { get; set; }

    public string Typedocument { get; set; }

    public int Iddocument { get; set; }

    public int Matagentrenvoi { get; set; }
}