// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.TitreDeTransportModelsEF;

public partial class Roleutilisateur
{
    public int Idroleutilisateur { get; set; }

    public string Slugroleutilisateur { get; set; }

    public string Libelleroleutilisateur { get; set; }

    public virtual ICollection<Autorisationrole> Autorisationrole { get; set; } = new List<Autorisationrole>();
}