// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.TitreDeTransportModelsEF;

/// <summary>
/// Table des titres de transports
/// </summary>
public partial class Titredetransport
{
    public int Idtitre { get; set; }

    public int? Idremb { get; set; }

    public int? Idbonp { get; set; }

    public int? Idcompagnie { get; set; }

    public int? Idagencevoyage { get; set; }

    public int? Idfacture { get; set; }

    public int Idetape { get; set; }

    public int? Idclasse { get; set; }

    public string Reffichemission { get; set; }

    public decimal Montanttitret { get; set; }

    public string Reftitret { get; set; }

    public DateTime Datesaititret { get; set; }

    public DateTime? Datevaltitret { get; set; }

    public string Obstitret { get; set; }

    public int Matagentsaititret { get; set; }

    public int? Matagentvaltitret { get; set; }

    public string Routing { get; set; }

    public DateTime Datedepart { get; set; }

    public DateTime Dateretour { get; set; }

    public int Matagentbeneficiaire { get; set; }

    public int? Idrenvoititret { get; set; }

    public virtual Agencevoyage IdagencevoyageNavigation { get; set; }

    public virtual Bondepassage IdbonpNavigation { get; set; }

    public virtual Classevoyage IdclasseNavigation { get; set; }

    public virtual Compagnie IdcompagnieNavigation { get; set; }

    public virtual Etape IdetapeNavigation { get; set; }

    public virtual Facture IdfactureNavigation { get; set; }

    public virtual Remboursement IdrembNavigation { get; set; }
}