// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.OrdreDeMissionDBModelsEF;

public partial class FicheDeMission
{
    public string RefFiche { get; set; }

    public int? Idagent { get; set; }

    public string Objet { get; set; }

    public DateTime? DateDébut { get; set; }

    public DateTime? DateFin { get; set; }

    public int? Idopérateur { get; set; }

    public int? Valider { get; set; }

    public int? Idvalideur { get; set; }

    public DateTime? DateEnreg { get; set; }

    public string ImputationBudgétaire { get; set; }

    public DateTime? DateRetMisPre { get; set; }

    public DateTime? DateTransfCr { get; set; }

    public DateTime? DateAppOrdRec { get; set; }

    public DateTime? DateRecOrdRec { get; set; }

    public DateTime? DateDepDec { get; set; }

    public int? RoutingTraite { get; set; }

    public int? RoutingPvalider { get; set; }

    public int? RoutingValider { get; set; }

    public int? DépenseValider { get; set; }

    public int? Etat { get; set; }

    public string Frais { get; set; }

    public string AutreImputation { get; set; }

    public int? ControleTraite { get; set; }

    public string CatégorieAppliquée { get; set; }

    public string TransportPerso { get; set; }

    public string SignataireOm { get; set; }

    public DateTime? DateRouting { get; set; }

    public string MissionDrh { get; set; }

    public string CodeStrImputation { get; set; }

    public int? Etape { get; set; }

    public string Numvoiture { get; set; }

    /// <summary>
    /// Code du projet
    /// </summary>
    public string Codeprojet { get; set; }

    /// <summary>
    /// Intitulé abrégé du projet
    /// </summary>
    public string Titreabregeprojet { get; set; }

    /// <summary>
    /// Intitulé du projet
    /// </summary>
    public string Intituleprojet { get; set; }

    public bool ImpressionDefinitive { get; set; }

    public int? Budget { get; set; }

    public int? Consommer { get; set; }

    public int? Disponible { get; set; }

    public string Villedepart { get; set; }

    public string SignataireRetourMission { get; set; }

    public byte[] Fichierdecompte { get; set; }

    public string SignataireDecompte { get; set; }

    public string SignataireDecompte2 { get; set; }

    public bool Autoriserchevauchement { get; set; }
}