// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.OrdreDeMissionDBModelsEF;

public partial class Routing3
{
    public string RefFiche { get; set; }

    public short? Nligne { get; set; }

    public string Depart { get; set; }

    public string Arrive { get; set; }

    public string MoyenTransport { get; set; }

    public string Transporteur { get; set; }

    public string DetailTransporteur { get; set; }

    public DateTime? DateD { get; set; }

    public string PaysDepart { get; set; }

    public string PaysArrive { get; set; }
}