// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.OrdreDeMissionDBModelsEF;

public partial class Routing2
{
    public short? Nligne { get; set; }

    public string RefFiche { get; set; }

    public string Pays { get; set; }

    public string Ville { get; set; }

    public string Hotel { get; set; }

    public DateTime? Du { get; set; }

    public DateTime? Au { get; set; }

    public short? NbreJrs { get; set; }

    public int? Mtindemnite { get; set; }

    public int? Mthebergement { get; set; }

    public decimal? Change { get; set; }

    public DateTime? DuHeb { get; set; }

    public DateTime? AuHeb { get; set; }
}