// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Gestions_des_Titres_de_Transport.OrdreDeMissionDBModelsEF;

public partial class Routing1
{
    public string RefFiche { get; set; }

    public DateTime? DateDepart { get; set; }

    public DateTime? DateRetour { get; set; }

    public int? OperateurM { get; set; }

    public short? Valider { get; set; }

    public int? ValiderParM { get; set; }

    public short? Pvalider { get; set; }

    public int? PvaliderParM { get; set; }

    public DateTime? DateEn { get; set; }

    public string Routing { get; set; }

    public int? MontantBillet { get; set; }

    public string Nature { get; set; }

    public DateTime? DateVisa { get; set; }

    public DateTime? DateValidation { get; set; }
}